baseURL = "https://blog.prabeeshk.com/"
languageCode = "en-us"
title = "This is One of the Solutions"
description = "A technical blog covering programming, data engineering, Apache Spark, embedded systems, CUDA programming, and software development best practices. Practical tutorials and insights for developers."
theme = "ananke"
enableRobotsTXT = true
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

# Performance optimizations
enableGitInfo = false
enableEmoji = false
disableKinds = ["taxonomy", "term"]

# Updated pagination configuration
[pagination]
pagerSize = 9

# Fix deprecated permalink token
[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"
    bonus = "/bonus/:contentbasename/"

[params]
    favicon = "/images/favicon.png"
    recent_posts_number = 15
    twitter = "https://twitter.com/prabeesh_k"
    linkedin = "https://www.linkedin.com/in/prabeeshk/"
    show_reading_time = true
     
    # Social media
    twitter_creator = "@prabeesh_k"
    twitter_site = "@prabeesh_k"
    
    # Performance
    enable_minify = true
    enable_gzip = true
    enable_brotli = true
    enable_resource_hints = true
    enable_critical_css = true

# Disqus configuration - new format
[services]
[services.disqus]
    Shortname = "prabeeshk"

[markup.goldmark.renderer]
    unsafe= true

# Enhanced sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Output formats for better performance
[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"
    isPlainText = true
    notAlternative = true

# Minify configuration
[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = true
      keepWhitespace = false
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.svg]
      keepComments = false
      precision = 1
