baseURL = "https://blog.prabeeshk.com/"
languageCode = "en-us"
title = "This is One of the Solutions"
description = "A technical blog covering programming, data engineering, Apache Spark, embedded systems, CUDA programming, and software development best practices. Practical tutorials and insights for developers."
theme = "ananke"
enableRobotsTXT = true
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

# Updated pagination configuration
[pagination]
pagerSize = 9

# Fix deprecated permalink token
[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"

[params]
    favicon = "/images/favicon.png"
    recent_posts_number = 15
    twitter = "https://twitter.com/prabeesh_k"
    linkedin = "https://www.linkedin.com/in/prabeeshk/"
    show_reading_time = true

# Disqus configuration - new format
[services]
[services.disqus]
    Shortname = "prabeeshk"

[markup.goldmark.renderer]
    unsafe= true


