baseURL = "https://prabeesh.github.io/"
languageCode = "en-us"
title = "This is the one of the solutions"
theme = "ananke"
googleAnalytics = "UA-56250765-2"
enableRobotsTXT = true
disqusShortname = "prabeeshk"
MetaDataFormat = "yaml"
Paginate = 9
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"
