baseURL = "https://prabeesh.github.io"
languageCode = "en-us"
title = "This is the one of the solutions"
theme = "ananke"
googleAnalytics = "UA-56250765-2"
enableRobotsTXT = true
disqusShortname = "prabeeshk"
MetaDataFormat = "yaml"
Paginate = 9
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params]
    favicon = "/images/favicon.png"
    recent_posts_number = 15
    twitter = "https://twitter.com/prabeesh_k"
    linkedin = "https://www.linkedin.com/in/prabeeshk/"

[markup.goldmark.renderer]
    unsafe= true
