baseURL = "https://blog.prabeeshk.com/"
languageCode = "en-us"
title = "This is One of the Solutions"
description = "A technical blog covering programming, data engineering, Apache Spark, embedded systems, CUDA programming, and software development best practices. Practical tutorials and insights for developers."
theme = "ananke"
enableRobotsTXT = true
disqusShortname = "prabeeshk"
MetaDataFormat = "yaml"
Paginate = 9
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

# Fix deprecated permalink token
    [permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params]
    favicon = "/images/favicon.png"
    recent_posts_number = 15
    twitter = "https://twitter.com/prabeesh_k"
    linkedin = "https://www.linkedin.com/in/prabeeshk/"

[markup.goldmark.renderer]
    unsafe= true


