baseURL = "https://blog.prabeeshk.com/"
languageCode = "en-us"
title = "This is One of the Solutions"
description = "Welcome to This is One of the Solutions, a technical blog where I share practical insights and tutorials on programming, data engineering, Apache Spark, embedded systems, and modern software development practices. Explore in-depth articles, code examples, and real-world solutions to help you tackle complex technical challenges."
theme = "ananke"
enableRobotsTXT = true
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

enableGitInfo = false
enableEmoji = false
disableKinds = ["taxonomy", "term"]

canonifyURLs = true
rssLimit = 20

[pagination]
pagerSize = 9

[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"
    bonus = "/bonus/:contentbasename/"

[params]
    favicon = "/images/favicon.png"
    recent_posts_number = 15
    twitter = "https://twitter.com/prabeesh_k"
    linkedin = "https://www.linkedin.com/in/prabeeshk/"
    show_reading_time = true
    google_analytics = "G-PECLCLL5R6"
    twitter_creator = "@prabeesh_k"
    twitter_site = "@prabeesh_k"
    images = ["/images/og-image.png"]
    author = "Prabeesh Keezhathra"

[services]
[services.disqus]
    Shortname = "prabeeshk"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = true
      keepWhitespace = false
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.svg]
      keepComments = false
      precision = 1

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
    anonymizeIP = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "keywords"
    weight = 150
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10
